service:
  name: converter-ts
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-jest-plugin
package:
  exclude:
    - node_modules/**
    - test/**
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
functions:
  convertProperties2Json:
    handler: src/ConvertProperties2Json.default
    description: Convert Properties to Json
    events:
      - http:
          method: post
          path: converter/properties/json
  convertJson2Yaml:
    handler: src/ConvertJson2Yaml.default
    description: Convert Json to Yaml
    events:
      - http:
          method: post
          path: converter/json/yaml
