service:
  name: aws-nodejs-typescript
plugins:
  - serverless-webpack
package:
  exclude:
    - node_modules/**
    - test/**
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
functions:
  convertProperties2Json:
    handler: src/handler.convertProperties2Json
    description: Convert Properties to Json
    events:
      - http:
          method: post
          path: converter/properties/json
